### ISSUE TITLE
ArgumentException: The Assembly UnityEditor.CoreModule

### ISSUE THREAD

**Issue by muveso** [neon-age/Unity-Bridge-API#1]
I downloaded your source and open as project on Unity but it gives namespace errors? 

```
ArgumentException: The Assembly UnityEditor.CoreModule is referenced by AV.BridgeAPI ('Assets/AV.BridgeAPI.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <b8968fbbb2c44f7fa1b07fef0419683f>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <b8968fbbb2c44f7fa1b07fef0419683f>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <b8968fbbb2c44f7fa1b07fef0419683f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

**Comment by neon-age** [comment]
Oh? I think OpenSesame creates the .dll in Assets folder by default. 
It should not exist in the project itself, only used outside - so just delete it

**Comment by muveso** [comment]
@neon-age Actually I just want to use physics raycast bridge on mobile. so I deleted all other UI and shadergraph bridges and build .dll.

I can use this dll on editor but when I want to build project to android, it gives error.

ArgumentException: The Assembly UnityEditor.CoreModule

**Comment by neon-age** [comment]
Make sure that .dll has Validate References unchecked

**Comment by muveso** [comment]
@neon-age it gives same error.

```
ArgumentException: The Assembly UnityEditor.CoreModule is referenced by AV.BridgeAPI ('Assets/AV.BridgeAPI.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <ad50112e30b445fdbf80d5814c3cbcf6>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <ad50112e30b445fdbf80d5814c3cbcf6>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <ad50112e30b445fdbf80d5814c3cbcf6>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

**Comment by neon-age** [comment]
That's an issue, haven't tested in build before. I guess I'd have to make a separate .dll for Editor stuff.. 
For now you can remove all Editor related scripts

**Comment by muveso** [comment]
@neon-age Actually I deleted all files except _Physics and _Engine files. I think this files doesn’t releated any Editor sources. but still it gives same error. 

Can you please test it on build?

**Comment by neon-age** [comment]
Indeed. This happens because .asmdef automatically references both UnityEngine and UnityEditor.
I'm not yet sure if there is an easy way to fix this..

**Comment by neon-age** [comment]
I'll try to use Roslyn compiler as .dll for publishing, instead of relying on OpenSesame.
This way we can choose which references and scripts it will compile and include.

**Comment by muveso** [comment]
@neon-age okay! please let me know if it works. 

then maybe other raycast methods will be implemented as well.

**Comment by muveso** [comment]
@neon-age I tried Roslyn myself but I don’t know too much about assemblies. did you succeed?

**Comment by neon-age** [comment]
Yes I did - the stupendous way to fix this was to just temporarily overwrite AsmdexEx.cs with nothing, so it is excluded from compilation. Now it builds just fine!

With Roslyn as .dll I've got it to build a simple _Physics script, but in more complex cases, like _VisualElement - it throws compile errors (most likely to the fact that IgnoreAccessChecksTo attribute is not added automatically, only by OpenSesame).

While I'm restructuring the project, here's a [OpenSesame publish fix.zip](https://github.com/neon-age/Unity-Bridge-API/files/7668633/OpenSesame.publish.fix.zip)
(you need to put a modified InspectorGUI.cs in Open Sesame Compiler package, that is embedded in a project. 
RoslynAsDllCompiler is not required, but you may wanna take a look)

**Comment by muveso** [comment]
@neon-age I don't clearly understand. I modified InspectorGUI.cs as you said and make a build but it gives same error at all?

**Comment by neon-age** [comment]
> I wonder how can we find private api's for Unity Physics?

I use Rider for go-to-definition decompiling, it is perfect. Alternative is dnSpy https://github.com/dnSpy/dnSpy

**Comment by muveso** [comment]
@neon-age I want to ask you smt, can we just use rigidbody functions as well? 
someRigid.AddForce() to someRigid.AddForceInjected() maybe..

**Comment by neon-age** [comment]
Sometimes there is just nothing to optimize:
![image](https://user-images.githubusercontent.com/29812914/145047152-34d885f1-d2f4-405f-a462-fb8d0a679f60.png)
Use Deep Profiler to see what the method is actually doing and how it affects the performance.

**Comment by neon-age** [comment]
@muveso here's a non-dev build performance tests:
![image](https://user-images.githubusercontent.com/29812914/145169543-62ac2f5d-c822-4fb7-acc0-1c8ef4713f3c.png)
Expect only a 1.5~1.8x speedup on mobile. Depends on a device and case complexity

**Comment by muveso** [comment]
@neon-age it is still performant way to use. how did you profile scripts on mobile non-dev build?

**Comment by neon-age** [comment]
Profiler slows down methods a lot, thus gives an incorrect info, so I just use a new Stopwatch() in non-dev

**Comment by muveso** [comment]
@neon-age I don't get much performance gain (x1.5) so there is no magic. but it can provide a small optimization, for example when using too many physics functions.
